dbt_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{env_var('HOST', 'host.docker.internal')}}"
      user: "{{env_var('USER', 'postgres')}}"
      password: "{{env_var('PASSWORD', 'postgres')}}"
      port: "{{env_var('PORT', '5432') | int }}"
      dbname: "{{env_var('DBNAME', 'postgres')}}"
      schema: "{{env_var('SCHEMA', 'public')}}"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds